### ISSUE TITLE
reth Node Not Sending NewBlock/NewBlockHashes Messages to bloXroute Gateway

### ISSUE THREAD

**Issue by bogdanprodanj** [bnb-chain/reth-bsc-trail#204]
The `reth` node broadcasts the following events to connected peers:
```
Total messages received: 26000, 
Transactions messages received: 183, 
NewPooledTransactionHashes messages received: 20530, 
GetBlockHeaders messages received: 8, 
BlockHeaders messages received: 1, 
GetBlockBodies messages received: 52, 
GetPooledTransactions messages received: 3, 
PooledTransactions messages received: 5223
```
Is there a specific reason why the node is not sending `NewBlock` and `NewBlockHashes` messages to other peers?

P.S. When running `geth` node, it does send `NewBlock` and `NewBlockHashes` messages.

**Comment by yutianwu** [comment]
Can you share more information about the network you used? For example, what was the start command of the reth node?

**Comment by bogdanprodanj** [comment]
@yutianwu the starting command was

```
nohup /usr/local/bin/bsc-reth-b node --full --chain bsc --datadir /home/linux-user/node/reth --http --http.api web3,eth,net,debug,trace,txpool,rpc,admin --ws --ws.api web3,eth,net,debug,trace,txpool,rpc --authrpc.jwtsecret=/home/ec2-user/node/reth/jwtsecret --authrpc.addr 0.0.0.0 --authrpc.port 8551 --enable-prefetch --optimize.enable-execution-cache > nohup.out 2>&1 &
```

The rest of the config was pretty standard.

**Comment by yutianwu** [comment]
> NewBlock

Thank you. How did you get the messages you mentioned? Is there a simple way I can reproduce it?

**Comment by bogdanprodanj** [comment]
I run [bloxRoute gateway](https://docs.bloxroute.com/gateway/hosted-and-local-gateways/gateway-installation/startup-arguments) locally with `--multi-node=enode://<node_public_key>@<reth_node_ip>:30303` arg. 
I modified the gateway's code to get the message and print all the incoming messages from the `reth` node. However, this can be achieved just by modifying the `reth` node and log all the outgoing messages for the gateway (gateway will print something like `INFO [12-09|10:36:34.697] Started P2P networking self=enode://<gw_public_key>@127.0.0.1:0`)

**Comment by yutianwu** [comment]
> I run [bloxRoute gateway](https://docs.bloxroute.com/gateway/hosted-and-local-gateways/gateway-installation/startup-arguments) locally with `--multi-node=enode://<node_public_key>@<reth_node_ip>:30303` arg. I modified the gateway's code to get the message and print all the incoming messages from the `reth` node. However, this can be achieved just by modifying the `reth` node and log all the outgoing messages for the gateway (gateway will print something like `INFO [12-09|10:36:34.697] Started P2P networking self=enode://<gw_public_key>@127.0.0.1:0`)

Hi, did you try using reth nodes for opBNB or Ethereum? We don't change the code of the p2p based on https://github.com/paradigmxyz/reth. Can you help us check the other networks? If other networks also don't emit the events, we may need to raise an issue in https://github.com/paradigmxyz/reth.

**Comment by yutianwu** [comment]
> I run [bloxRoute gateway](https://docs.bloxroute.com/gateway/hosted-and-local-gateways/gateway-installation/startup-arguments) locally with `--multi-node=enode://<node_public_key>@<reth_node_ip>:30303` arg. I modified the gateway's code to get the message and print all the incoming messages from the `reth` node. However, this can be achieved just by modifying the `reth` node and log all the outgoing messages for the gateway (gateway will print something like `INFO [12-09|10:36:34.697] Started P2P networking self=enode://<gw_public_key>@127.0.0.1:0`)

Hi, it seems that `NewBlockHashes` events are not emitted by design. We don't rely on such events for reth nodes. So the events that you mentioned may not be added in the future.

**Comment by bogdanprodanj** [comment]
Thanks for the explanation!
