### ISSUE TITLE
assertion left != right failed. Can it be the sidecar feature?

### ISSUE THREAD

**Issue by zhk101** [bnb-chain/reth-bsc-trail#62]
### Describe the bug

I am using `bsc-reth` and my node instance is currently syncing the chain from scratch (node started with --full flag)
Currently at the execution stage. Today I have rebuild `bsc-reth` with the latest `develop` branch, that now includes the sidecar support feature (#45)
After restarting the node with the new binary, The node panics with the message `assertion left != right failed: A static file <> database inconsistency was found that would trigger an unwind to block 0`.

After going back to the previous binary (without #45) the node picks up where it left and continue syncing/executing.

### Steps to reproduce

1. Build bsc-geth with a commit prior to #45 commit. 
2. Start as a full node (--full flag)
3. Wait for it to sync and get to execution stage
4. Upgrade `bsc-reth` with latest `develop` (or #45 commit)
5. Start the node

### Node logs

```text
2024-07-10T14:37:33.247800Z  INFO Verifying storage consistency.
2024-07-10T14:37:33.308331Z  INFO Setting unwind target. checkpoint_block_number=40103919 unwind_target=0 segment=Sidecars
thread 'main' panicked at /node/bsc-reth/reth/crates/node/builder/src/launch/common.rs:372:13:
assertion left != right failed: A static file <> database inconsistency was found that would trigger an unwind to block 0
  left: Unwind(0)
 right: Unwind(0)
stack backtrace:
   0: rust_begin_unwind
   1: core::panicking::panic_fmt
   2: core::panicking::assert_failed_inner
   3: core::panicking::assert_failed
   4: reth_node_builder::launch::common::LaunchContextWith<reth_node_builder::launch::common::Attached<reth_node_builder::launch::common::WithConfigs,DB>>::create_provider_factory::{{closure}}
   5: <reth_node_builder::launch::DefaultNodeLauncher as reth_node_builder::launch::LaunchNode<reth_node_builder::builder::states::NodeBuilderWithComponents<T,CB>>>::launch_node::{{closure}}
   6: reth_cli_runner::run_to_completion_or_panic::{{closure}}
   7: reth::cli::Cli<Ext>::run
   8: bsc_reth::main
note: Some details are omitted, run with RUST_BACKTRACE=full for a verbose backtrace.
```

### Platform(s)

Linux (x86)

### What version/commit are you on?

e11ee4898

### What database version are you on?

2

### Which chain / network are you on?

bsc (56)

### What type of node are you running?

Full via --full flag

### What prune config do you use, if any?

[prune.parts]
sender_recovery = { distance = 2_592_000 } 

transaction_lookup = { distance = 2_592_000 }

receipts = { distance = 2_592_000 }

account_history = { distance = 2_592_000 } 

storage_history = { distance = 2_592_000 }
```

### If you've built Reth from source, provide the full command you used

cargo build --bin bsc-reth --features "bsc jemalloc asm-keccak" --profile "maxperf"

### Code of Conduct

- [X] I agree to follow the Code of Conduct

**Comment by pythonberg1997** [comment]
Yes, this new version is not forward compatible. 
You could:
1. sync from 0 using the newest version
2. revert `feat: add support of block sidecars for bsc (#45)` commit and build the node
3. waiting for a fix version
