### ISSUE TITLE
debug_traceBlockByNumber  error -32003

### ISSUE THREAD

**Issue by snf** [bnb-chain/reth-bsc-trail#96]
### Describe the bug

This should return a block trace but instead return -32003. I tried with other blocks around this and all seem ok.
```
$ curl -X POST --data '{"jsonrpc":"2.0","method":"debug_traceBlockByNumber","params":["0x23ef5b2", {"tracer": "callTracer", "tracerConfig":{"withLog":true}}],"id":1}' -H "Content-Type: application/json" "http://localhost:8745/"
{"jsonrpc":"2.0","error":{"code":-32003,"message":"insufficient funds for gas * price + value"},"id":1}
```

### Steps to reproduce

Archive node synced using the snapshots from https://github.com/fuzzland/snapshots

### Node logs

```text
Nothing of interest in the logs.
```

### Platform(s)

Linux (x86)

### What version/commit are you on?

c3361c9744268d81d60eb75d3622fd1ef81b81d4

### What database version are you on?

Current database version: 2
Local database version: 2

### Which chain / network are you on?

mainnet

### What type of node are you running?

Archive (default)

### Code of Conduct

- [X] I agree to follow the Code of Conduct

**Comment by snf** [comment]
Narrowed down to the transaction 0xc5ece05471170fc2150353c896b482862ae49f6d075920fec5266d3d586ef6be

```
$ curl -X POST --data '{"jsonrpc":"2.0","method":"debug_traceTransaction","params":["0xc5ece05471170fc2150353c896b482862ae49f6d075920fec5266d3d586ef6be", {"tracer": "callTracer"}],"id":1}' -H "Content-Type: application/json" "http://localhost:8745"
{"jsonrpc":"2.0","error":{"code":-32003,"message":"insufficient funds for gas * price + value"},"id":1}
```

**Comment by snf** [comment]
Also found other ones. All seem to be the deposit transaction:

```
$ curl -X POST --data '{"jsonrpc":"2.0","method":"debug_traceTransaction","params":["0x8ae5d89316359af8a552aa52df36c00882e540c089d8369b00ffbd44fcfacc1a", {"tracer": "callTracer"}],"id":1}' -H "Content-Type: application/json" "http://localhost:8745"
{"jsonrpc":"2.0","error":{"code":-32003,"message":"insufficient funds for gas * price + value"},"id":1}

$ curl -X POST --data '{"jsonrpc":"2.0","method":"debug_traceTransaction","params":["0xd9f2984a572eb9663c59fdcdee126e4ca29ed739baf4d6bde3b1803fcf28598b", {"tracer": "callTracer"}],"id":1}' -H "Content-Type: application/json" "http://localhost:8745"
{"jsonrpc":"2.0","error":{"code":-32003,"message":"insufficient funds for gas * price + value"},"id":1}
```

**Comment by keefel** [comment]
Currently, the `debug_traceBlockByNumber` interface for BSC Reth is not yet available, leading to errors due to the execution of system transactions. We are actively working to address this issue and will provide updates on the progress of the fix.

**Comment by snf** [comment]
If you have ideas why it works with syncing and not using the debug_* interfaces, I can try making a PR.

**Comment by pythonberg1997** [comment]
We tried to fix this. Could you please help test this branch(https://github.com/bnb-chain/reth/tree/roshan/parlia) to see if it works? @snf

**Comment by snf** [comment]
Awesome, thanks @pythonberg1997! It works with the traces I had written down. I'll run my test pipeline this week and report back if I see any unexpected error.

**Comment by pythonberg1997** [comment]
I will close the issue. Feel free to  reopen it if any problem.
